blog/urls.py
from django.urls import path
from . import views


app_name = "blog"
urlpatterns = [
    path("", views.index, name="index"),
    path("home", views.home, name="home"), 
    path("flights", views.flights, name="flights"),
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/book", views.book, name="book")
]

blogDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include("blog.urls")),
    path("users/", include("users.urls") )
]

users/urls.py
from django.urls import path
from .  import views
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout")
]

blog/models.py
from django.db import models

class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code}) "    

class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()


    def __str__(self):
        return f"{self.id}:  {self.origin} to {self.destination}"


class Passenger(models.Model):
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flight, blank=True, related_name="passengers")

    def __str__(self):
        return f"{self.first} {self.last}"

users/models.py
from django.db import models

# Create your models here.

blog/views.py
from .models import Flight, Passenger
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django import forms
from django.urls import reverse

class TestForm(forms.Form):
    test = forms.CharField(max_length=12)

def index(request):
    if request.method == "POST":
        form = TestForm(request.POST)
        if form.is_valid():
            test = form.cleaned_data["test"]
            request.session["testlist"] += [test]
            return HttpResponseRedirect(reverse("blog:home"))
        else:
            return render(request, "blog/index.html", {
                "form": form
            })    
    return render(request, "blog/index.html", {
        "form": TestForm()
    })

def home(request):
    if "testlist" not in request.session:
        request.session["testlist"] = []
    return render(request, "blog/home.html", {
        "testlist": request.session["testlist"]
    })

def flights(request):
    return render(request, "blog/flights.html", {
        "flights": Flight.objects.all()
        })

def flight(request, flight_id):
    flight = Flight.objects.get(id=flight_id)
    return render(request, "blog/flight.html", {
        "flight": flight,
        "passengers": flight.passengers.all(),
        "non_passengers": Passenger.objects.exclude(flights=flight).all()
        })        



def book(request, flight_id):
    if request.method == "POST":
        flight = Flight.objects.get(pk=flight_id)
        passenger = Passenger.objects.get(pk=int(request.POST["passenger"]))
        passenger.flight.add(flight)
        return HttpResponseRedirect(reverse("blog:flight", args=(flight.id)))

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    return render(request, "users/user.html")    


def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else: 
            return render(request, "users/login.html", {
                "message": "Invalid credentials."
            })
    return render(request, "users/login.html")


def logout_view(request):
    logout(request)
    return render(request, "users/login.html", {
        "message": "Logged out."
    })
    pass

blog/templates/blog/flight.html
{% extends "blog/layout.html" %}

{% block content %}
<h1>Flight {{ flight.id }} </h1>
<ul>
    <li>Origin: {{ flight.origin }}</li>
    <li>Destination: {{ flight.destination }} </li>
    <li>Duration: {{ flight.duration }} </li>
</ul>

<h2>Passengers</h2>
<ul>
    {% for passenger in passengers %}
        <li>{{ passenger }} </li>
        {% empty %}
        <li>No passengers</li>
    {% endfor %}
</ul>

<h2>Add Passenger</h2>
<form action="{% url 'blog:book' flight.id %}" method="post">
    {% csrf_token %}
    <select name="passenger" >
        {% for passenger in non_passengers %}
            <option value="{{ passenger.id }} ">{{ passenger }}</option>
        {% endfor %}
    </select>
    <input type="submit">
</form>

<a href="{% url 'blog:flights' %} ">Back to the flights</a>
{% endblock content %} 

blog/templates/blog/flights.html
{% extends "blog/layout.html" %}

{% block content %}
<h1>Fligths</h1>
<ul>
    {% for flight in flights %}
        <li> 
            <a href="{% url 'blog:flight' flight.id %} ">Flight: {{ flight.id }}: {{ flight.origin }} to {{ flight.destination }}  </a>
        </li>

    {% endfor %}
</ul>

{% endblock content %}

blog/templates/blog/home.html
{% extends "blog/layout.html" %}
{% block content %}
<body>
    <h1>home page</h1>
    <div class="container">
        <ul>
            {% for test in testlist %}
                <li>{{ test }}</li>
                {% empty %}
                <li>No Tasks.</li>
            {% endfor %}
        </ul>
        <a href="{% url 'blog:index' %}">Go to index page</a>
    </div>
   
</body>
{% endblock content %}    

blog/templates/blog/index.html
{% extends "blog/layout.html" %}
{% block content %}
<body>
    <h1>Example Blog.</h1>
    
    <div class="contianer">
        <form class="container", action="{% url 'blog:index' %}", method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit">
            <a href="{% url 'blog:home' %}">Go to home page</a>
        </form>
    </div>
    
</body>
{% endblock content %}    

blog/templates/blog/layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Blog</title>
        <link rel="stylesheet" href="{% static 'blog/styles.css' %}">
    </head>
    {% block content %}
    {% endblock content %}
</html>

users/templates/users/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Users</title>
    </head>
    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

users/templates/users/login.html
{% extends  "users/layout.html" %}
{% block content %}

    {% if message %}
        <div>{{ message }} </div>
    {% endif %}

    <form action="{% url 'login' %} " method="post" >
        {% csrf_token %}
        <input type="text", name="username", placeholder="Username">
        <input type="password", name="password", placeholder="Password">
        <input type="submit" value="Login">
    </form>
{% endblock content %}

users/templates/users/user.html
{% extends "users/layout.html" %}

{% block content %}
    <h1>Welcome, {{ request.user.first_name }} </h1>

    <ul>
        <li>Username: {{request.user.username}} </li>
        <li>Email: {{ request.user.email }} </li>
    </ul>

    <a href="{% url 'logout' %} ">Log Out</a>
{% endblock content %}